M48
; DRILL file KiCad 10.0.2 date 2026-05-30T16:51:17
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-30T16:51:17-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X167.945Y-103.29
X167.945Y-109.07
T2
X145.0Y-75.5
X145.0Y-131.0
X168.0Y-131.0
X168.5Y-75.5
M30
