M48
; DRILL file {KiCad 9.0.7} date 2026-04-25T21:26:05-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-25T21:26:05-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X194.86Y-103.555
X200.64Y-103.555
T2
X157.0Y-103.5
X157.0Y-126.5
X212.0Y-104.0
X212.0Y-126.0
M30
